### ISSUE TITLE
ExploreP2P Rating is not shown for some originators

### ISSUE THREAD

**Issue by jpadera** [DeeNaxic/mintos-extension#77]
When visiting a loan details, for some originators ExploreP2P Rating shows just "n/a". Here are some examples of loans with a missing rating:
Sun Finance Denmark https://www.mintos.com/cs/4425213-39
Sun Finance Kazakhstan https://www.mintos.com/cs/24705287-03
ID Finance Kazakhstan https://www.mintos.com/cs/19416569-01
Finko Moldova (Sebo) https://www.mintos.com/cs/16979072-03
Finko Armenia (Varks) https://www.mintos.com/cs/17527626-09
Finko Ukraine (UkrPozyka) https://www.mintos.com/cs/27605026-06
Other originators works fine.

**Comment by rafalkrupinski** [comment]
So basically multiple countries are not supported?

**Comment by jpadera** [comment]
Yes, it looks like that.
