### ISSUE TITLE
Parsing age, unemployment etc. is broken on loan page.

### ISSUE THREAD

**Issue by DeeNaxic** [DeeNaxic/mintos-extension#88]
They are broken in the sense that, they are not loaded at first, so the check runs, but it doesn't appear to find the string. Some times, it works, most the time it doesn't. The loading needs to be delayed to the page is actually fully loaded.

Test case where the age is above, and unemployed:
https://www.mintos.com/en/5735292-01

**The code**
![image](https://user-images.githubusercontent.com/19817781/82835846-7e201880-9ec5-11ea-84e8-fd9aec0e4172.png)

**Shows**
![image](https://user-images.githubusercontent.com/19817781/82835858-8c6e3480-9ec5-11ea-8200-8bb0153f56e1.png)

**Comment by rafalkrupinski** [comment]
I think this has been fixed :)
